export const baseTextStyles = {
  textSm: {
    color: "text",
    fontFamily: "gtAmericaMono",
    fontSize: 0,
    fontWeight: "regular",
    lineHeight: "large",
  },
  textBase: {
    color: "text",
    fontFamily: "gtSuperText",
    fontSize: 1,
    fontWeight: "regular",
    lineHeight: "large",
  },
  textLg: {
    color: "text",
    fontFamily: "gtSuperText",
    fontSize: 2,
    fontWeight: "regular",
    lineHeight: "medium",
  },
  textXl: {
    color: "text",
    fontFamily: "gtSuperDisplay",
    fontSize: 3,
    fontWeight: "bold",
    lineHeight: "medium",
  },
  text2Xl: {
    color: "text",
    fontFamily: "gtSuperDisplay",
    fontSize: 4,
    fontWeight: "regular",
    lineHeight: "small",
  },
  text3Xl: {
    color: "text",
    fontFamily: "gtSuperDisplay",
    fontSize: 5,
    fontWeight: "bold",
    lineHeight: "small",
  },
  text4Xl: {
    color: "text",
    fontFamily: "gtSuperDisplay",
    fontSize: 6,
    fontWeight: "bold",
    lineHeight: "small",
  },
}
